### ISSUE TITLE
Hey. I want to disable all sounds and voice, and just want the battery notification to come. What should I do. Please help asap if possible 🙏🏻

### ISSUE THREAD

**Issue by GokuDanAsh** [JustABeginning/Battery-Zira#7]
Hey. I want to disable all sounds and voice, and just want the battery notification to come. What should I do. Please help asap if possible 🙏🏻

_Originally posted by @GokuDanAsh in https://github.com/JustABeginning/Battery-Zira/discussions/1#discussioncomment-2556577_

**Comment by JustABeginning** [comment]
An attempt has been made to fix it in [v2.0](https://github.com/JustABeginning/Battery-Zira/releases/tag/v2.0). Check it out 😊  !

**Comment by GokuDanAsh** [comment]
Thank You very much, brother.

**Comment by JustABeginning** [comment]
You are welcome 👍
